services:
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  auth-api:
    build: ../auth-api
    container_name: auth_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-api.rule=Host(`auth.localhost`)"
      - "traefik.http.services.auth-api.loadbalancer.server.port=8081"
    depends_on:
      - redis
      - traefik

  todos-api:
    build: ../todos-api
    container_name: todos_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos-api.rule=Host(`todos.localhost`)"
      - "traefik.http.services.todos-api.loadbalancer.server.port=8082"
    depends_on:
      - redis
      - auth-api
      - traefik

  users-api:
    build: ../users-api
    container_name: users_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-api.rule=Host(`users.localhost`)"
      - "traefik.http.services.users-api.loadbalancer.server.port=8083"
    depends_on:
      - redis
      - auth-api
      - traefik

  frontend:
    build: ../frontend
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    depends_on:
      - todos-api
      - users-api
      - auth-api
      - traefik

  log-message-processor:
    build: ../log-message-processor
    container_name: log_message_processor
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.log-message-processor.rule=Host(`log.localhost`)"
      - "traefik.http.services.log-message-processor.loadbalancer.server.port=80"
    depends_on:
      - redis
      - traefik

volumes:
  redis_data:
